version: '3'
services:
  dockernet:
    build: .
    ports:
      - "5000:80"
  # Unleash related stuffs
  unleash:
    image: unleashorg/unleash-server:3.1
    ports:
      - "5002:4242"
    environment:
      DATABASE_URL: postgres://postgres:unleash@db/postgres
    depends_on:
      - db
  db:
    expose:
      - "5432"
    image: postgres:10-alpine